# Generated by Django 6.0.3 on 2026-03-16 06:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encryptedmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(max_length=100, null=True)),
                ('textcontent', models.CharField(max_length=100, null=True)),
                ('filekey', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('encfilepath', models.CharField(max_length=100, null=True)),
                ('decfilepath', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'encryptmodel',
            },
        ),
        migrations.CreateModel(
            name='Filerequestmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileid', models.CharField(max_length=100, null=True)),
                ('useremail', models.EmailField(max_length=254, null=True)),
                ('textcontent', models.CharField(max_length=100, null=True)),
                ('receiveremail', models.CharField(max_length=100, null=True)),
                ('filekey', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
            options={
                'db_table': 'filerequest',
            },
        ),
        migrations.CreateModel(
            name='userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(default='Deactivated', max_length=100)),
            ],
            options={
                'db_table': 'userreg',
            },
        ),
    ]
