# Generated by Django 6.0.3 on 2026-03-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedmodel',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encryptedmodel',
            name='filetype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
