# Generated by Django 6.0.3 on 2026-03-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_encryptedmodel_filename_encryptedmodel_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
